version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_URI_TEST=${MONGO_URI_TEST}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    env_file:
      - .env

volumes:
  mongo_data: